language: python

matrix:
  include:
    - os: osx
    language: generic
    env: TOXENV=3.6
    - os: osx
    language: generic
    env: TOXENV=3.7
    - os: osx
    language: generic
    env: TOXENV=3.5

install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python=$TOXENV
  - conda activate test
  - pip install -e .

script:
  - pytest

notifications:
  email: false
